Fix/include mazay (#9)
* Wreckfest Wrapper tooltip IDs to start with no. 1

* Fix export for Linux

* Rebrand as Toolbox Mz

Fix wiki link, remove warning

* Update README.md

* Automatic .bmap builder

* Include Bugmenu addon in toolbox

Added simple addon loader

* Add bake animation option to preferences

Animation bake adds one keyframe to each Blender frame.

* Add exporter back to export menu

* Fix automatic build for Linux

* Add BagEdit to Bugmenu

* Fix context missing active object error

Error was triggered by hiding active object

* Fix error with nodegroup without node tree

Fixed error: 'NoneType' object has no attribute 'name'

* Create CREDITS.md

* Update documentation link

* Fix error with Wreckfest wrapper

Moved path handling code into one place for consistency. Wreckfest wrapper is now:
- Checking against failed path solve
- Accepting png
- Building bmap

---------

Co-authored-by: gmazy <gmazy@runbox.com>